"""GitHub Issue READ/WRITE boundary -- request builders, REST Provider Adapter, normalizer.

GitHub Issue P0 semantics: `resource_type = TASK`. This module is the only
place in the codebase that calls the GitHub REST API. Semantic input
(repository/state/assignee/label for reads; repository/title/body/issue_number
for writes) is deterministically compiled into a GitHub request here -- no
GitHub Search DSL or free-form mutation body is ever generated by an LLM or
accepted from outside this connector. Normalized results carry GitHub-owned
metadata (repository, issue_number, labels, assignees, url) alongside
connector-neutral TASK-semantic fields; they are not the shared Domain TASK
schema and are not converted into a Google Task shape.

WRITE mutations only reach the GitHub API; they are not wired to Approval,
Claim, Verification, or Recovery -- that Runtime integration is a later step.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from enum import StrEnum
from typing import Protocol, cast
from urllib.error import HTTPError, URLError
from urllib.parse import urlencode
from urllib.request import Request, urlopen

from google_work_agent.mcp.github_auth import (
    GitHubCredentialProvider,
    GitHubReauthenticationRequired,
)

GITHUB_API_BASE = "https://api.github.com"
GITHUB_API_VERSION = "2022-11-28"
GITHUB_API_TIMEOUT_SECONDS = 30
GITHUB_ISSUE_LIST_PAGE_SIZE = "100"


class GitHubIssueQueryError(RuntimeError):
    """Raised when the typed P0 semantic filter fails deterministic validation."""

    def __init__(self, safe_code: str) -> None:
        super().__init__(safe_code)
        self.safe_code = safe_code


class GitHubProviderError(RuntimeError):
    """Sanitized failure from the GitHub Issue Provider Adapter.

    ``dispatch_started`` records whether the request may have already
    reached GitHub, mirroring the existing MCP Tool error contract.
    """

    def __init__(self, safe_code: str, *, dispatch_started: bool = False) -> None:
        super().__init__(safe_code)
        self.safe_code = safe_code
        self.dispatch_started = dispatch_started


class GitHubIssueState(StrEnum):
    """The only state filter values github_list_issues accepts."""

    OPEN = "OPEN"
    CLOSED = "CLOSED"
    ALL = "ALL"


_STATE_PARAM_VALUES: dict[GitHubIssueState, str] = {
    GitHubIssueState.OPEN: "open",
    GitHubIssueState.CLOSED: "closed",
    GitHubIssueState.ALL: "all",
}


def _validate_repository(repository: str) -> str:
    parts = repository.split("/")
    if len(parts) != 2 or not parts[0].strip() or not parts[1].strip():
        raise GitHubIssueQueryError("REPOSITORY_INVALID")
    return repository


@dataclass(frozen=True, slots=True)
class GitHubIssueListQuery:
    """Typed P0 semantic filter for github_list_issues -- nothing beyond this."""

    repository: str
    state: GitHubIssueState = GitHubIssueState.OPEN
    assignee: str | None = None
    label: str | None = None

    def __post_init__(self) -> None:
        _validate_repository(self.repository)
        if self.assignee is not None and not self.assignee.strip():
            raise GitHubIssueQueryError("ASSIGNEE_INVALID")
        if self.label is not None and not self.label.strip():
            raise GitHubIssueQueryError("LABEL_INVALID")


@dataclass(frozen=True, slots=True)
class GitHubIssueRequest:
    """A fully-materialized, deterministic GitHub REST request."""

    url: str


def build_issue_list_request(query: GitHubIssueListQuery) -> GitHubIssueRequest:
    """Compile a typed semantic filter into a deterministic GitHub request.

    The same ``query`` value always produces the same ``url`` -- filter keys
    are added in a fixed order and there is no free-form query parameter.
    """

    params: dict[str, str] = {
        "state": _STATE_PARAM_VALUES[query.state],
        "per_page": GITHUB_ISSUE_LIST_PAGE_SIZE,
    }
    if query.assignee is not None:
        params["assignee"] = query.assignee
    if query.label is not None:
        params["labels"] = query.label
    url = f"{GITHUB_API_BASE}/repos/{query.repository}/issues?{urlencode(params)}"
    return GitHubIssueRequest(url=url)


def _validate_issue_number(issue_number: int) -> None:
    if issue_number < 1:
        raise GitHubIssueQueryError("ISSUE_NUMBER_INVALID")


def build_issue_get_request(*, repository: str, issue_number: int) -> GitHubIssueRequest:
    _validate_repository(repository)
    _validate_issue_number(issue_number)
    return GitHubIssueRequest(url=f"{GITHUB_API_BASE}/repos/{repository}/issues/{issue_number}")


@dataclass(frozen=True, slots=True)
class GitHubIssueCreateInput:
    """Typed P0 semantic input for github_create_issue -- nothing beyond this."""

    repository: str
    title: str
    body: str | None = None

    def __post_init__(self) -> None:
        _validate_repository(self.repository)
        if not self.title.strip():
            raise GitHubIssueQueryError("TITLE_INVALID")


@dataclass(frozen=True, slots=True)
class GitHubIssueUpdateInput:
    """Typed P0 semantic input for github_update_issue -- title and/or body."""

    repository: str
    issue_number: int
    title: str | None = None
    body: str | None = None

    def __post_init__(self) -> None:
        _validate_repository(self.repository)
        _validate_issue_number(self.issue_number)
        if self.title is None and self.body is None:
            raise GitHubIssueQueryError("EMPTY_UPDATE")
        if self.title is not None and not self.title.strip():
            raise GitHubIssueQueryError("TITLE_INVALID")


@dataclass(frozen=True, slots=True)
class GitHubIssueStateChangeInput:
    """Typed P0 semantic input shared by github_close_issue/github_reopen_issue."""

    repository: str
    issue_number: int

    def __post_init__(self) -> None:
        _validate_repository(self.repository)
        _validate_issue_number(self.issue_number)


@dataclass(frozen=True, slots=True)
class GitHubIssueMutationRequest:
    """A fully-materialized, deterministic GitHub REST mutation request."""

    method: str
    url: str
    body: dict[str, object]


def build_issue_create_request(create: GitHubIssueCreateInput) -> GitHubIssueMutationRequest:
    """Compile a typed create input into a deterministic POST request.

    The same ``create`` value always produces the same method/url/body.
    """

    body: dict[str, object] = {"title": create.title}
    if create.body is not None:
        body["body"] = create.body
    return GitHubIssueMutationRequest(
        method="POST",
        url=f"{GITHUB_API_BASE}/repos/{create.repository}/issues",
        body=body,
    )


def build_issue_update_request(update: GitHubIssueUpdateInput) -> GitHubIssueMutationRequest:
    """Compile a typed update input into a deterministic PATCH request."""

    body: dict[str, object] = {}
    if update.title is not None:
        body["title"] = update.title
    if update.body is not None:
        body["body"] = update.body
    return GitHubIssueMutationRequest(
        method="PATCH",
        url=f"{GITHUB_API_BASE}/repos/{update.repository}/issues/{update.issue_number}",
        body=body,
    )


def build_issue_close_request(change: GitHubIssueStateChangeInput) -> GitHubIssueMutationRequest:
    return GitHubIssueMutationRequest(
        method="PATCH",
        url=f"{GITHUB_API_BASE}/repos/{change.repository}/issues/{change.issue_number}",
        body={"state": "closed"},
    )


def build_issue_reopen_request(change: GitHubIssueStateChangeInput) -> GitHubIssueMutationRequest:
    return GitHubIssueMutationRequest(
        method="PATCH",
        url=f"{GITHUB_API_BASE}/repos/{change.repository}/issues/{change.issue_number}",
        body={"state": "open"},
    )


@dataclass(frozen=True, slots=True)
class GitHubRestResponse:
    """One GitHub REST response -- status and parsed body, success or not."""

    status_code: int
    body: object


class GitHubRestTransport(Protocol):
    """Minimal boundary for the GitHub REST API (fakeable in tests).

    One ``request`` method covers both reads (GET, no body) and mutations
    (POST/PATCH, JSON body) -- the same GitHub host, auth header, and JSON
    envelope apply to both, so a single transport abstraction stays cohesive
    instead of forking into a read-only and a write-only client.
    """

    def request(
        self, method: str, url: str, *, access_token: str, body: dict[str, object] | None = None
    ) -> GitHubRestResponse:
        """Perform one authenticated request and return status + parsed JSON body."""


class UrllibGitHubRestTransport:
    """Real GitHub REST transport. The only network calls this module makes."""

    def request(
        self, method: str, url: str, *, access_token: str, body: dict[str, object] | None = None
    ) -> GitHubRestResponse:
        headers = {
            "Authorization": f"Bearer {access_token}",
            "Accept": "application/vnd.github+json",
            "X-GitHub-Api-Version": GITHUB_API_VERSION,
        }
        data: bytes | None = None
        if body is not None:
            data = json.dumps(body).encode("utf-8")
            headers["Content-Type"] = "application/json"
        request = Request(url, data=data, headers=headers, method=method)
        try:
            # nosec B310: fixed GitHub API host, not a user-controlled URL.
            with urlopen(request, timeout=GITHUB_API_TIMEOUT_SECONDS) as response:
                return GitHubRestResponse(
                    status_code=response.status, body=_parse_json_or_none(response.read())
                )
        except HTTPError as error:
            return GitHubRestResponse(
                status_code=error.code, body=_parse_json_or_none(error.read())
            )
        except (URLError, TimeoutError) as error:
            # A mutating verb may have already left the process before the
            # network failed -- GitHub's receipt of it is genuinely unknown,
            # so dispatch_started must stay True and callers must not retry
            # blindly. GET is idempotent/side-effect-free, so False is safe.
            raise GitHubProviderError(
                "MCP_UNAVAILABLE", dispatch_started=(method != "GET")
            ) from error


def _parse_json_or_none(raw: bytes) -> object:
    if not raw:
        return None
    try:
        return json.loads(raw.decode("utf-8"))
    except (UnicodeDecodeError, json.JSONDecodeError):
        return None


_STATUS_CODE_SAFE_CODES: dict[int, str] = {
    401: "REAUTH_REQUIRED",
    403: "PERMISSION_DENIED",
    404: "NOT_FOUND",
    422: "INVALID_ARGUMENT",
    429: "RATE_LIMITED",
}


def _safe_code_for_status(status_code: int) -> str:
    if status_code in _STATUS_CODE_SAFE_CODES:
        return _STATUS_CODE_SAFE_CODES[status_code]
    if status_code >= 500:
        return "UPSTREAM_5XX"
    return "GITHUB_REQUEST_FAILED"


class GitHubIssueProviderAdapter:
    """The only component allowed to call the GitHub Issues REST API."""

    def __init__(
        self,
        *,
        credential_provider: GitHubCredentialProvider,
        transport: GitHubRestTransport | None = None,
    ) -> None:
        self._credential_provider = credential_provider
        self._transport = transport or UrllibGitHubRestTransport()

    def list_issues(self, query: GitHubIssueListQuery) -> list[dict[str, object]]:
        body = self._perform_and_get_body(build_issue_list_request(query))
        if not isinstance(body, list):
            raise GitHubProviderError("MALFORMED_RESPONSE", dispatch_started=True)
        return [item for item in body if isinstance(item, dict)]

    def get_issue(self, *, repository: str, issue_number: int) -> dict[str, object]:
        request = build_issue_get_request(repository=repository, issue_number=issue_number)
        body = self._perform_and_get_body(request)
        if not isinstance(body, dict):
            raise GitHubProviderError("MALFORMED_RESPONSE", dispatch_started=True)
        return body

    def create_issue(self, create: GitHubIssueCreateInput) -> dict[str, object]:
        return self._perform_mutation(build_issue_create_request(create))

    def update_issue(self, update: GitHubIssueUpdateInput) -> dict[str, object]:
        self._ensure_target_is_an_issue(
            repository=update.repository, issue_number=update.issue_number
        )
        return self._perform_mutation(build_issue_update_request(update))

    def close_issue(self, change: GitHubIssueStateChangeInput) -> dict[str, object]:
        self._ensure_target_is_an_issue(
            repository=change.repository, issue_number=change.issue_number
        )
        return self._perform_mutation(build_issue_close_request(change))

    def reopen_issue(self, change: GitHubIssueStateChangeInput) -> dict[str, object]:
        self._ensure_target_is_an_issue(
            repository=change.repository, issue_number=change.issue_number
        )
        return self._perform_mutation(build_issue_reopen_request(change))

    def _ensure_target_is_an_issue(self, *, repository: str, issue_number: int) -> None:
        """Reject a Pull Request target before any mutating PATCH is dispatched.

        Reuses the existing READ path (`get_issue` + `normalize_github_issue`)
        instead of a new Preflight/Safety framework. Any failure here --
        including "it's a PR" -- means the mutation itself was never sent, so
        it is always reported with dispatch_started=False regardless of the
        precheck GET's own dispatch_started value.
        """

        try:
            raw = self.get_issue(repository=repository, issue_number=issue_number)
            normalize_github_issue(raw, repository=repository)
        except GitHubProviderError as error:
            raise GitHubProviderError(error.safe_code, dispatch_started=False) from error

    def _perform_and_get_body(self, request: GitHubIssueRequest) -> object:
        access_token = self._access_token()
        response = self._transport.request("GET", request.url, access_token=access_token)
        if response.status_code == 200:
            return response.body
        if response.status_code == 401:
            self._credential_provider.invalidate_access_token()
        raise GitHubProviderError(
            _safe_code_for_status(response.status_code), dispatch_started=True
        )

    def _perform_mutation(self, request: GitHubIssueMutationRequest) -> dict[str, object]:
        access_token = self._access_token()
        response = self._transport.request(
            request.method, request.url, access_token=access_token, body=request.body
        )
        if response.status_code in (200, 201):
            if not isinstance(response.body, dict):
                raise GitHubProviderError("MALFORMED_RESPONSE", dispatch_started=True)
            return response.body
        if response.status_code == 401:
            self._credential_provider.invalidate_access_token()
        raise GitHubProviderError(
            _safe_code_for_status(response.status_code), dispatch_started=True
        )

    def _access_token(self) -> str:
        try:
            return self._credential_provider.get_access_token()
        except GitHubReauthenticationRequired as error:
            raise GitHubProviderError("REAUTH_REQUIRED") from error


class GitHubIssueTaskState(StrEnum):
    """Connector-neutral TASK-semantic state derived from GitHub's raw `state`."""

    OPEN = "OPEN"
    CLOSED = "CLOSED"


@dataclass(frozen=True, slots=True)
class GitHubIssueResourceIdentity:
    """Deterministic, repository-scoped identity -- never collides across repos."""

    repository: str
    issue_number: int

    @property
    def external_resource_id(self) -> str:
        return f"{self.repository}#{self.issue_number}"


@dataclass(frozen=True, slots=True)
class GitHubIssueTaskView:
    """Connector-owned TASK-semantic normalization of one GitHub Issue.

    Not the shared Domain TASK schema and not a Google Task DTO -- GitHub
    Issue-specific metadata (repository/issue_number/labels/assignees/url)
    stays namespaced on this connector-local type.
    """

    resource_identity: GitHubIssueResourceIdentity
    title: str
    description: str
    task_state: GitHubIssueTaskState
    url: str
    labels: tuple[str, ...]
    assignees: tuple[str, ...]


def normalize_github_issue(raw: dict[str, object], *, repository: str) -> GitHubIssueTaskView:
    """Normalize one raw GitHub Issue DTO. Never returns the raw DTO itself.

    GitHub's Issues REST endpoints (both list and single-item GET) can also
    return Pull Requests, identifiable only by a `pull_request` key. Pull
    Requests are out of P0 scope and must never become a TASK result --
    reject deterministically instead of silently normalizing one.
    """

    if "pull_request" in raw:
        raise GitHubProviderError("NOT_FOUND", dispatch_started=True)
    issue_number = raw.get("number")
    title = raw.get("title")
    if not isinstance(issue_number, int) or not isinstance(title, str):
        raise GitHubProviderError("MALFORMED_RESPONSE", dispatch_started=True)
    body = raw.get("body")
    url = raw.get("html_url")
    return GitHubIssueTaskView(
        resource_identity=GitHubIssueResourceIdentity(
            repository=repository, issue_number=issue_number
        ),
        title=title,
        description=body if isinstance(body, str) else "",
        task_state=(
            GitHubIssueTaskState.CLOSED
            if raw.get("state") == "closed"
            else GitHubIssueTaskState.OPEN
        ),
        url=url if isinstance(url, str) else "",
        labels=_normalized_labels(raw),
        assignees=_normalized_assignees(raw),
    )


def normalize_github_issue_list(
    raw_items: list[dict[str, object]], *, repository: str
) -> list[GitHubIssueTaskView]:
    """Normalize a raw issue list, dropping pull requests.

    GitHub's "list repository issues" endpoint also returns pull requests
    (distinguishable only by the presence of a `pull_request` key); GitHub
    Issue P0 scope is issues only.
    """

    return [
        normalize_github_issue(item, repository=repository)
        for item in raw_items
        if "pull_request" not in item
    ]


def _normalized_labels(raw: dict[str, object]) -> tuple[str, ...]:
    labels = raw.get("labels")
    if not isinstance(labels, list):
        return ()
    return tuple(
        sorted(
            cast(str, label["name"])
            for label in labels
            if isinstance(label, dict) and isinstance(label.get("name"), str)
        )
    )


def _normalized_assignees(raw: dict[str, object]) -> tuple[str, ...]:
    assignees = raw.get("assignees")
    if not isinstance(assignees, list):
        return ()
    return tuple(
        sorted(
            cast(str, assignee["login"])
            for assignee in assignees
            if isinstance(assignee, dict) and isinstance(assignee.get("login"), str)
        )
    )
